HW9/SportsSite/Models/LocationDetail.cs
namespace SportsSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class LocationDetail
    {
        public LocationDetail()
        {
            Results = new HashSet<Result>();
        }
        public int ID { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        [Required]
        [StringLength(50)]
        public string Place { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}

HW9/SportsSite/Controllers/LocationDetailsController.cs
/* This controller adds a new location to the db. 
 * Auto generated LocationDetails controller stripped of unnecessary */

using System.Linq;
using System.Web.Mvc;
using SportsSite.Models;
using SportsSite.Models.DAL;

namespace SportsSite.Controllers
{
    public class LocationDetailsController : Controller
    {
        private SportsContext db = new SportsContext();

        // GET: LocationDetails
        public ActionResult Index()
        {
            return View(db.LocationDetails.ToList());
        }

        // GET: LocationDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocationDetails/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Date,Place")] LocationDetail locationDetail)
        {
            if (ModelState.IsValid)
            {
                db.LocationDetails.Add(locationDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(locationDetail);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW9/SportsSite/Views/LocationDetails/Create.cshtml
@model SportsSite.Models.LocationDetail
   
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddEvent</title>
</head>
<body>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h2>Add New Event Information</h2>
        <hr />
        <div class="row">
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.Date, new { placeholder = "Date", @class = "boxes" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.Place, new { placeholder = "Location", @class = "boxes" })
                @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <br /><br /><img src="~/Content/Images/icons2.png" class="img-fluid" width="252" height="250" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" value="Submit New" class="myButton" /><br>
                @Html.ActionLink("Back to Homepage", "Index", "Home", null, new { @class = "myButton" })
            </div>
        </div>
    }
</body>
</html>

HW9/SportsSite/Views/LocationDetails/Index.cshtml
@model IEnumerable<SportsSite.Models.LocationDetail>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewLocationDetails</title>
</head>
<body>
    <div class="row">
        <div class="col-md-10">
            @Html.ActionLink("Add Another Event", "Create", "LocationDetails", null, new { @class = "myButton" })
            @Html.ActionLink("Back to Homepage", "Index", "Home", null, new { @class = "myButton" })
            <table class="table" id="t01">
                <tr>
                    <th>Date</th>
                    <th>Location</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Place)
                        </td>
                    </tr>
                }
            </table>
            @Html.ActionLink("Add Another Event", "Create", "LocationDetails", null, new { @class = "myButton" })
            @Html.ActionLink("Back to Homepage", "Index", "Home", null, new { @class = "myButton" })
        </div>
    </div>
</body>
</html>